### ISSUE TITLE
CloudBBQ

### ISSUE THREAD

**Issue by boris327** [gleeds/cloudbbq#14]
![Capture](https://user-images.githubusercontent.com/54038990/103288507-ab99eb00-49ed-11eb-88ac-73a8dd39e7fb.JPG)
![Capture](https://user-images.githubusercontent.com/54038990/103281097-a5e6da00-49da-11eb-8042-0e35d061f195.JPG)
Hi Greg,
First of all, thank you for your work.
I have a problem running the "npm start" (image attached).
I am working on a windows computer and I have installed visual studio, node-js, and noble.
Please help me.

**Comment by gleeds** [comment]
I've only tested this so far on MacOS and Linux, so I'm not sure if Windows is adding any extra variables to things, but the first error looks like a problem with the MQTT server your are using.  Out of curiosity, are you using Adafruit IO or something else, and if something else, does it have a valid HTTPS certificate?

**Comment by gleeds** [comment]
Closing this since I didn't get a response.  Feel free to reopen with details if you still need help.
