### ISSUE TITLE
Error message on Mac OSX

### ISSUE THREAD

**Issue by thebdizzle** [gleeds/cloudbbq#18]
Hi there,
Firstly, awesome work on this! I've just gotten into smoking and I think this is gonna be awesome.
I'm getting an error message on mac os x. Everything seemed to install ok, and it's picking up the thermometer, but I'm just getting a repeating error and nothing seems to be making it to the broker. Any ideas?

```
> cloudbbq@1.0.0 start
> node app.js

iBBQ Discovered
(node:18415) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
paired
setting units
sending start temp events
wierd empty or wrong size buffer
wierd empty or wrong size buffer
wierd empty or wrong size buffer
wierd empty or wrong size buffer
wierd empty or wrong size buffer
wierd empty or wrong size buffer
wierd empty or wrong size buffer
wierd empty or wrong size buffer
wierd empty or wrong size buffer
wierd empty or wrong size buffer
wierd empty or wrong size buffer
wierd empty or wrong size buffer
wierd empty or wrong size buffer
```

It just repeats like that on and on.

Thanks!

**Comment by gleeds** [comment]
Hmm, seems like that's really close to working.  You have connected to the unit and are receiving messages (it sends one update a second) which means the handshake and setup was successful, cloudbbq is just unhappy about the data it's getting back.  Can you let me know which model you are using, and how many probes you have connected?

**Comment by gleeds** [comment]
You could also try adding something like this to line 137:
`console.log(data.length)`

**Comment by thebdizzle** [comment]
Thanks I’ll try add that to the console and see what happens. I’m using an inkbird int-4xs. For that test I just had one probe connected, but it is a 4 probe model.

**Comment by thebdizzle** [comment]
Ok I added that line in and now I'm getting the number 8 after each wrong buffer line -

```
> cloudbbq@1.0.0 start
> node app.js

iBBQ Discovered
(node:19905) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
paired
setting units
sending start temp events
8
wierd empty or wrong size buffer
8
wierd empty or wrong size buffer
8
wierd empty or wrong size buffer
8
wierd empty or wrong size buffer
8
wierd empty or wrong size buffer
8
wierd empty or wrong size buffer
```

This time I tried it with all 4 probes attached, just in case that was making a difference.
Thanks again for the assistance!

**Comment by gleeds** [comment]
The unit I have has 6 probes.  I knew there were other models and manufactures using the same white label hardware and app but with less probes, but I guess I assumed that they would just send null values for the probe slots they didn't have.  I'm going to guess that it was a bad assumption and instead I need a config option to set how many probes your unit has.

If that log statement above spits out `8` for your unit, I think we'll have our answer and it should be pretty easy to modify.

**Comment by gleeds** [comment]
And my guess was right.

**Comment by gleeds** [comment]
Ok, basically everywhere there is a `6` or `12` hard coded I need to have that read from the config instead.  I can try to update it tonight.

**Comment by thebdizzle** [comment]
You're an absolute legend. If there's anything I can do to assist let me know! Is there somewhere I can donate to you for the hard work?

**Comment by gleeds** [comment]
Alright, update the new `probes` value in your `config/default.json` to `4` and give it a shot.

**Comment by thebdizzle** [comment]
It's working! Amazing, thank you so much! One final question - is there some way to set the temperature to Celcius? I had the device itself set to C through the app, but cloudbbq is setting the probes to F when it connects. I'm sure there's a simple setting I'm just missing somewhere. I can't thank you enough for this.

**Comment by gleeds** [comment]
So the good news is the device always sends the temp in celsius regardless of what it displays on the screen and I convert it to _freedom units_ before displaying them.

**Comment by thebdizzle** [comment]
Awesome! Is there somewhere easy I can turn that off? And is there somewhere that you’re telling it to display F on the display? So sorry for all the questions, I hope I don’t come across as Buggy! Just excited to try out a cook with this tomorrow!

**Comment by gleeds** [comment]
Alright, I went ahead and pushed one more update.  there is now a localization section in the `default.json` you can set to `F` or `C`.

**Comment by thebdizzle** [comment]
Just wanted to thank you for such an amazing app and for taking the time to help me out. It’s working a real treat, I have a pork shoulder in now and have it all running through my home assistant instance essentially turning a Bluetooth thermometer into a wifi one. Really appreciate it.
![474796A3-949C-4B33-BC8B-B836864222C6](https://user-images.githubusercontent.com/6408066/111822300-bb173900-8937-11eb-974b-0a09ef3d09ff.png)
