### ISSUE TITLE
docker-compose.yml

### ISSUE THREAD

**Issue by sogood007** [gleeds/cloudbbq#24]
https://github.com/gleeds/cloudbbq/blob/0f5a942476ffda8ec04123eaa37cfd89167baf82/docker-compose.yml#L7

Is the directory supposed to be app/config , because the Dockerfile create the app directory
      - ./default.json:/app/config/default.json

**Comment by gleeds** [comment]
Yeah, that's not quite right.  When I tested it I think I assumed that it would error out with the placeholder default.json but I guess that's not the case.  I'll update it.

Also I'm looking into completely replacing the docker volume mount configuration approach with environmental variables instead.

**Comment by gleeds** [comment]
Alright, so, ignore what I said before, instead I went ahead and pushed up my branch with the environmental variables support which is a much more idiomatic docker way of doing this.  If you don't want to edit the source, you should be able to just download the `docker-compose.yaml` file, edit the `environment:` options you want, and `docker-compose up -d`.  There are a few optional ones that are supported but that I didn't stub out in the compose file, that you can see in `config/custom-environment-variables.json`. I'll be adding more mappings to get everything in the `default.json` eventually, but the docker support I would still kinda call beta.  I'll update documentation once I feel it's more stable.

**Comment by sogood007** [comment]
Thanks a lot for the quick fix. I love to have environment support.
